### ISSUE TITLE
A simple roadmap

### ISSUE THREAD

**Issue by hecmay** [cornell-zhang/uptune#7]
- [x] Switch to async task scheduler to better utilize compute power 
- [x] Use SQLAlchemy + Panda DF as global DB -- OpenTuner's built-in DB too slow 
- [x] New examples (e.g. Vitis/AOC/NVCC/GCC) and exhaustive database for fast querying
- [x] Introduced a virtual python file system to avoid the write conflicts from different tuning threads
- [ ] Evaluate search engines on the exhaustive database (e.g. DQN, general meta-heuristics)
- [x] Support user-specified rules (e.g. restrict variable A's search space if another variable B==3)

```python
@ut.rule
def dynamic_space(vars):
    if vars.paramA > 20: 
        vars.paramB.space = ["on", "auto"]
```

- [x] Support querying logic (e.g. return all working configs that can satisfy the input requirement). If history found, query the existing records that meet the requirements, otherwise start searching until hitting any qualifying schedules 

```python
ut.restrict 
def query(vars):
    # restrict tuning variable and covariate (observed) values
    if vars.paramA > 20 and vars.cache_hit_rate > 0.4:
        return vars.qor

```
- [x] Updated the logging system. An example of output log
```shell
(test) [sx233@vsl085 intel-aocl]$ ut tune_aocl.py -pf 32 -rt 72000 --timeout 7200000
[ INFO ] Uptune work directory /homes/sx233/uptune-1/samples/intel-aocl
[ INFO ] Performing dynamic analysis...
[ INFO ] Cleaning up the legacy work folder...
[ INFO ] Single-stage(intrusive), threads(32), test-limit(5000), timeout(8:00:00), build-timeout(20:00:00)
[ INFO ] 6:15:17(#0/5000)   - QoR LW(-71.43)/LB(-296.29)/GB(-296.29) - build time(22513.79s)
[ INFO ] 12:20:47(#32/5000) - QoR LW(-67.67)/LB(-281.21)/GB(-296.29) - build time(21887.10s)
[ INFO ] 18:21:18(#64/5000) - QoR LW(-64.53)/LB(-294.98)/GB(-296.29) - build time(21590.21s)
```
